### PR TITLE
update to aff 4.0 and spec 2.0

### PR DESCRIPTION
**Pull request by justinwoo**

### CODE REVIEW

**Comment by justinwoo** [comment]
@felixSchl do you also manage this package?

**Comment by felixSchl** [comment]
Hey, sorry no, I did not even know it existed until now.

**Comment by justinwoo** [comment]
Can we have this merged if there's no big problems? We need this for a Aff 4.0 package set

**Comment by coltfred** [comment]
The lack of this causes a pretty bad newbie experience. I tried to get some basic tests added to my new project and had to add this branch as a dependency....

In case others need to do that before this is merged. `bower install -D 'justinwoo/purescript-spec-quickcheck#aff-4.0-spec-2.0'` does it.

**Comment by owickstrom** [comment]
Thanks for the PR @justinwoo !

**Comment by owickstrom** [comment]
`purescript-spec-quickcheck` now released as 2.0.0.

**Pull request merged**
